-- Family Quest shared shopping list
create table if not exists public.shopping_items (
  id bigint generated by default as identity primary key,
  text text not null,
  done boolean not null default false,
  source text not null default 'app',
  created_at timestamptz not null default now()
);

alter table public.shopping_items enable row level security;

create policy "shopping items readable" on public.shopping_items for select using (true);
create policy "shopping items insertable" on public.shopping_items for insert with check (true);
create policy "shopping items updatable" on public.shopping_items for update using (true);
create policy "shopping items deletable" on public.shopping_items for delete using (true);
