-- Apply as the database owner in Supabase SQL Editor. Preserves existing shopping rows.
begin;
create table if not exists public.shopping_items (
  id bigint generated by default as identity primary key,
  text text not null,
  done boolean not null default false,
  source text not null default 'app',
  created_at timestamptz not null default now()
);
alter table public.shopping_items enable row level security;
drop policy if exists "shopping items readable" on public.shopping_items;
drop policy if exists "shopping items insertable" on public.shopping_items;
drop policy if exists "shopping items updatable" on public.shopping_items;
drop policy if exists "shopping items deletable" on public.shopping_items;
revoke all on public.shopping_items from public, anon, authenticated;
grant select, insert, update, delete on public.shopping_items to service_role;
revoke all on sequence public.shopping_items_id_seq from public, anon, authenticated;
grant usage, select on sequence public.shopping_items_id_seq to service_role;

create table if not exists public.alexa_shopping_requests (
  request_id text primary key,
  created_at timestamptz not null default now()
);
alter table public.alexa_shopping_requests enable row level security;
revoke all on public.alexa_shopping_requests from public, anon, authenticated;
grant select, insert, delete on public.alexa_shopping_requests to service_role;

create or replace function public.add_alexa_shopping_items(p_request_id text, p_items text[])
returns void language plpgsql security invoker set search_path = '' as $$
begin
  if p_request_id is null or length(p_request_id) not between 1 and 512
    or coalesce(cardinality(p_items), 0) not between 1 and 10
    or exists (select 1 from unnest(p_items) as item where item is null or length(btrim(item)) not between 1 and 120)
  then raise exception 'Invalid shopping request'; end if;
  insert into public.alexa_shopping_requests(request_id) values (p_request_id) on conflict do nothing;
  if not found then return; end if;
  insert into public.shopping_items(text, done, source) select btrim(item), false, 'alexa' from unnest(p_items) as item;
  delete from public.alexa_shopping_requests where created_at < now() - interval '1 day';
end;
$$;
revoke all on function public.add_alexa_shopping_items(text, text[]) from public, anon, authenticated;
grant execute on function public.add_alexa_shopping_items(text, text[]) to service_role;
commit;
